backend code
DarkShadow20/Ecommerce-Backend pull request #1
Opened 2021-04-30 08:13 UTC by DarkShadow20

2021-05-01 00:08 UTC, DanishOnGit commented on router/cart-router.js
> +      res.json(normalizedCartItems);
minor refactor ,good practice: `res.status(200).json({success:true,noramalizedCartItems})`

2021-05-04 06:31 UTC, Rupamdas832 requested changes
Nicely written code. All the best practices. No hard changes according to me required.

2021-05-04 06:31 UTC, Rupamdas832 commented on models/products-model.js
> +async function fillProductsCollection() {
Its better you use ES6 syntax everywhere. Like 

const fillProductsCollection = () => { 
}

2021-05-04 06:31 UTC, Rupamdas832 commented on index.js
> +// run once
You can remove the comments once done.

2021-05-04 08:35 UTC, merged